### ISSUE TITLE
Nice work!

### ISSUE THREAD

**Issue by swbouman** [fwolfst/ECU-ESP8266#1]
Hey fwolfst,

im happy to see you are investing time to the zigbee project based on patience. 

I’m interested in this new project you created, due to the bugs, the other program has. 

Can you please provide a how-to install your program on an esp? 

Could it be possible to add inverter update option in the program? I had several inverters not responding when the Sun was bright, no harvest at that time. By ota update with an original Ecu-r the inverters are producing right now. 

There is an example of putting its update to the inverters online. I can search for the code if you want. 

Kinda regards and keep up the good work!

**Comment by fwolfst** [comment]
Hey @swbouman, thanks for the kind words and the offer with researching that code.

If you know how to program and compile stuff we could have a conversation, but otherwise the project is just an experiment and far away from doing anything that @patience4711 s solution is providing. There is a web-ui, but its really just to debug some zigbee code, right now.

And I doubt that I will have the patience (*coughcough*) and resources to develop it into anything like that. Most likely I will loose interest if I can read out the data of my one inverter and show it on a display or send it out via lorawan. Sorry.

That said, if there is someone wanting to and able to contribute on a code-level, I am all-in (but would probably try to collaborate with that person and patience in order to refactor that project, since it provides already so much functionality).

I will close this issue here, but feel free to reach out and keep an eye open for updates, who knows.
